import pytz
import logging


log = logging.getLogger(__name__)

def tz_is_valid(tz):
    try:
        pytz.timezone(tz)
    except:
        return False

    return True

tzlist_basic = [
    { 'name': 'Hawaii', 'value': 'Pacific/Honolulu', 'offset': '-10:00' },
    { 'name': 'Alaska', 'value': 'America/Anchorage', 'offset': '-09:00' },
    { 'name': 'Pacific Time (US & Canada)', 'value': 'America/Los_Angeles', 'offset': '-08:00' },
    { 'name': 'Mountain Time (US & Canada)', 'value': 'America/Denver', 'offset': '-07:00' },
    { 'name': 'Central Time (US & Canada)', 'value': 'America/Chicago', 'offset': '-06:00' },
    { 'name': 'Eastern Time (US & Canada)', 'value': 'America/New_York', 'offset': '-05:00' },
    { 'name': 'Atlantic Time (US & Canada)', 'value': 'Atlantic/Bermuda', 'offset': '-04:00' },
    { 'name': 'Newfoundland', 'value': 'Canada/Newfoundland', 'offset': '-03:30' },
    { 'name': 'Brazil, Buenos Aires, Georgetown', 'value': 'America/Buenos_Aires', 'offset': '-03:00' },
    { 'name': 'Mid-Atlantic', 'value': 'Atlantic/South_Georgia', 'offset': '-02:00' },
    { 'name': 'Azores, Cape Verde Islands', 'value': 'Atlantic/Cape_Verde', 'offset': '-01:00' },
    { 'name': 'Western Europe Time, London, Lisbon, Casablanca', 'value': 'Europe/London', 'offset': '+00:00' },
    { 'name': 'Brussels, Copenhagen, Madrid, Paris', 'value': 'Europe/Paris', 'offset': '+01:00' },
    { 'name': 'Kaliningrad, South Africa', 'value': 'Europe/Kaliningrad', 'offset': '+02:00' },
    { 'name': 'Baghdad, Riyadh, Moscow, St. Petersburg', 'value': 'Europe/Moscow', 'offset': '+03:00' },
    { 'name': 'Tehran', 'value': 'Asia/Tehran', 'offset': '+03:30' },
    { 'name': 'Abu Dhabi, Muscat, Baku, Tbilisi', 'value': 'Asia/Tbilisi', 'offset': '+04:00' },
    { 'name': 'Kabul', 'value': 'Asia/Kabul', 'offset': '+04:30' },
    { 'name': 'Ekaterinburg, Islamabad, Karachi, Tashkent', 'value': 'Asia/Tashkent', 'offset': '+05:00' },
    { 'name': 'Bombay, Calcutta, Madras, New Delhi', 'value': 'Asia/Calcutta', 'offset': '+05:30' },
    { 'name': 'Kathmandu', 'value': 'Asia/Kathmandu', 'offset': '+05:45' },
    { 'name': 'Almaty, Dhaka, Colombo', 'value': 'Asia/Colombo', 'offset': '+06:00' },
    { 'name': 'Bangkok, Hanoi, Jakarta', 'value': 'Asia/Bangkok', 'offset': '+07:00' },
    { 'name': 'Beijing, Perth, Singapore, Hong Kong', 'value': 'Asia/Singapore', 'offset': '+08:00' },
    { 'name': 'Tokyo, Seoul, Osaka, Sapporo, Yakutsi', 'value': 'Asia/Tokyo', 'offset': '+09:00' },
    { 'name': 'Adelaide, Darwin', 'value': 'Australia/Adelaide', 'offset': '+09:30' },
    { 'name': 'Eastern Australia, Guam, Vladivostok', 'value': 'Pacific/Guam', 'offset': '+10:00' },
    { 'name': 'Magadan, Solomon Islands, New Caledonia', 'value': 'Asia/Magadan', 'offset': '+11:00' },
    { 'name': 'Auckland, Wellington, Fiji, Kamchatka', 'value': 'Pacific/Auckland', 'offset': '+12:00' }
]

# has actual human-friendly display names
tzlist_useful = [{'capital': 'Andorra la Vella',
           'code': 'AD',
           'continent': 'Europe',
           'country_name': 'Andorra',
           'name': 'Andorra, Andorra la Vella',
           'value': 'Europe/Andorra'},
          {'capital': 'Kabul',
           'code': 'AF',
           'continent': 'Asia',
           'country_name': 'Afghanistan',
           'name': 'Afghanistan, Kabul',
           'value': 'Asia/Kabul'},
          {'capital': "St. John's",
           'code': 'AG',
           'continent': 'North America',
           'country_name': 'Antigua and Barbuda',
           'name': 'Antigua and Barbuda, Antigua',
           'value': 'America/Antigua'},
          {'capital': 'Tirana',
           'code': 'AL',
           'continent': 'Europe',
           'country_name': 'Albania',
           'name': 'Albania, Tirane',
           'value': 'Europe/Tirane'},
          {'capital': 'Yerevan',
           'code': 'AM',
           'continent': 'Asia',
           'country_name': 'Armenia',
           'name': 'Armenia, Yerevan',
           'value': 'Asia/Yerevan'},
          {'capital': 'Luanda',
           'code': 'AO',
           'continent': 'Africa',
           'country_name': 'Angola',
           'name': 'Angola, Luanda',
           'value': 'Africa/Luanda'},
          {'capital': 'Buenos Aires',
           'code': 'AR',
           'continent': 'South America',
           'country_name': 'Argentina',
           'name': 'Argentina, Buenos_Aires',
           'value': 'America/Argentina/Buenos_Aires'},
          {'capital': 'Buenos Aires',
           'code': 'AR',
           'continent': 'South America',
           'country_name': 'Argentina',
           'name': 'Argentina, Cordoba',
           'value': 'America/Argentina/Cordoba'},
          {'capital': 'Buenos Aires',
           'code': 'AR',
           'continent': 'South America',
           'country_name': 'Argentina',
           'name': 'Argentina, Jujuy',
           'value': 'America/Argentina/Jujuy'},
          {'capital': 'Buenos Aires',
           'code': 'AR',
           'continent': 'South America',
           'country_name': 'Argentina',
           'name': 'Argentina, Tucuman',
           'value': 'America/Argentina/Tucuman'},
          {'capital': 'Buenos Aires',
           'code': 'AR',
           'continent': 'South America',
           'country_name': 'Argentina',
           'name': 'Argentina, Catamarca',
           'value': 'America/Argentina/Catamarca'},
          {'capital': 'Buenos Aires',
           'code': 'AR',
           'continent': 'South America',
           'country_name': 'Argentina',
           'name': 'Argentina, La_Rioja',
           'value': 'America/Argentina/La_Rioja'},
          {'capital': 'Buenos Aires',
           'code': 'AR',
           'continent': 'South America',
           'country_name': 'Argentina',
           'name': 'Argentina, San_Juan',
           'value': 'America/Argentina/San_Juan'},
          {'capital': 'Buenos Aires',
           'code': 'AR',
           'continent': 'South America',
           'country_name': 'Argentina',
           'name': 'Argentina, Mendoza',
           'value': 'America/Argentina/Mendoza'},
          {'capital': 'Buenos Aires',
           'code': 'AR',
           'continent': 'South America',
           'country_name': 'Argentina',
           'name': 'Argentina, Rio_Gallegos',
           'value': 'America/Argentina/Rio_Gallegos'},
          {'capital': 'Buenos Aires',
           'code': 'AR',
           'continent': 'South America',
           'country_name': 'Argentina',
           'name': 'Argentina, Ushuaia',
           'value': 'America/Argentina/Ushuaia'},
          {'capital': 'Vienna',
           'code': 'AT',
           'continent': 'Europe',
           'country_name': 'Austria',
           'name': 'Austria, Vienna',
           'value': 'Europe/Vienna'},
          {'capital': 'Canberra',
           'code': 'AU',
           'continent': 'Oceania',
           'country_name': 'Australia',
           'name': 'Australia, Lord_Howe',
           'value': 'Australia/Lord_Howe'},
          {'capital': 'Canberra',
           'code': 'AU',
           'continent': 'Oceania',
           'country_name': 'Australia',
           'name': 'Australia, Hobart',
           'value': 'Australia/Hobart'},
          {'capital': 'Canberra',
           'code': 'AU',
           'continent': 'Oceania',
           'country_name': 'Australia',
           'name': 'Australia, Currie',
           'value': 'Australia/Currie'},
          {'capital': 'Canberra',
           'code': 'AU',
           'continent': 'Oceania',
           'country_name': 'Australia',
           'name': 'Australia, Melbourne',
           'value': 'Australia/Melbourne'},
          {'capital': 'Canberra',
           'code': 'AU',
           'continent': 'Oceania',
           'country_name': 'Australia',
           'name': 'Australia, Sydney',
           'value': 'Australia/Sydney'},
          {'capital': 'Canberra',
           'code': 'AU',
           'continent': 'Oceania',
           'country_name': 'Australia',
           'name': 'Australia, Broken_Hill',
           'value': 'Australia/Broken_Hill'},
          {'capital': 'Canberra',
           'code': 'AU',
           'continent': 'Oceania',
           'country_name': 'Australia',
           'name': 'Australia, Brisbane',
           'value': 'Australia/Brisbane'},
          {'capital': 'Canberra',
           'code': 'AU',
           'continent': 'Oceania',
           'country_name': 'Australia',
           'name': 'Australia, Lindeman',
           'value': 'Australia/Lindeman'},
          {'capital': 'Canberra',
           'code': 'AU',
           'continent': 'Oceania',
           'country_name': 'Australia',
           'name': 'Australia, Adelaide',
           'value': 'Australia/Adelaide'},
          {'capital': 'Canberra',
           'code': 'AU',
           'continent': 'Oceania',
           'country_name': 'Australia',
           'name': 'Australia, Darwin',
           'value': 'Australia/Darwin'},
          {'capital': 'Canberra',
           'code': 'AU',
           'continent': 'Oceania',
           'country_name': 'Australia',
           'name': 'Australia, Perth',
           'value': 'Australia/Perth'},
          {'capital': 'Baku',
           'code': 'AZ',
           'continent': 'Asia',
           'country_name': 'Azerbaijan',
           'name': 'Azerbaijan, Baku',
           'value': 'Asia/Baku'},
          {'capital': 'Bridgetown',
           'code': 'BB',
           'continent': 'North America',
           'country_name': 'Barbados',
           'name': 'Barbados, Bridgetown',
           'value': 'America/Barbados'},
          {'capital': 'Dhaka',
           'code': 'BD',
           'continent': 'Asia',
           'country_name': 'Bangladesh',
           'name': 'Bangladesh, Dhaka',
           'value': 'Asia/Dhaka'},
          {'capital': 'Brussels',
           'code': 'BE',
           'continent': 'Europe',
           'country_name': 'Belgium',
           'name': 'Belgium, Brussels',
           'value': 'Europe/Brussels'},
          {'capital': 'Ouagadougou',
           'code': 'BF',
           'continent': 'Africa',
           'country_name': 'Burkina Faso',
           'name': 'Burkina Faso, Ouagadougou',
           'value': 'Africa/Ouagadougou'},
          {'capital': 'Sofia',
           'code': 'BG',
           'continent': 'Europe',
           'country_name': 'Bulgaria',
           'name': 'Bulgaria, Sofia',
           'value': 'Europe/Sofia'},
          {'capital': 'Manama',
           'code': 'BH',
           'continent': 'Asia',
           'country_name': 'Bahrain',
           'name': 'Bahrain, Manama',
           'value': 'Asia/Bahrain'},
          {'capital': 'Bujumbura',
           'code': 'BI',
           'continent': 'Africa',
           'country_name': 'Burundi',
           'name': 'Burundi, Bujumbura',
           'value': 'Africa/Bujumbura'},
          {'capital': 'Porto-Novo',
           'code': 'BJ',
           'continent': 'Africa',
           'country_name': 'Benin',
           'name': 'Benin, Porto-Novo',
           'value': 'Africa/Porto-Novo'},
          {'capital': 'Bandar Seri Begawan',
           'code': 'BN',
           'continent': 'Asia',
           'country_name': 'Brunei Darussalam',
           'name': 'Brunei Darussalam, Brunei',
           'value': 'Asia/Brunei'},
          {'capital': 'Sucre',
           'code': 'BO',
           'continent': 'South America',
           'country_name': 'Bolivia',
           'name': 'Bolivia, La_Paz',
           'value': 'America/La_Paz'},
          {'capital': 'Brasília',
           'code': 'BR',
           'continent': 'South America',
           'country_name': 'Brazil',
           'name': 'Brazil, Noronha',
           'value': 'America/Noronha'},
          {'capital': 'Brasília',
           'code': 'BR',
           'continent': 'South America',
           'country_name': 'Brazil',
           'name': 'Brazil, Belem',
           'value': 'America/Belem'},
          {'capital': 'Brasília',
           'code': 'BR',
           'continent': 'South America',
           'country_name': 'Brazil',
           'name': 'Brazil, Fortaleza',
           'value': 'America/Fortaleza'},
          {'capital': 'Brasília',
           'code': 'BR',
           'continent': 'South America',
           'country_name': 'Brazil',
           'name': 'Brazil, Recife',
           'value': 'America/Recife'},
          {'capital': 'Brasília',
           'code': 'BR',
           'continent': 'South America',
           'country_name': 'Brazil',
           'name': 'Brazil, Araguaina',
           'value': 'America/Araguaina'},
          {'capital': 'Brasília',
           'code': 'BR',
           'continent': 'South America',
           'country_name': 'Brazil',
           'name': 'Brazil, Maceio',
           'value': 'America/Maceio'},
          {'capital': 'Brasília',
           'code': 'BR',
           'continent': 'South America',
           'country_name': 'Brazil',
           'name': 'Brazil, Bahia',
           'value': 'America/Bahia'},
          {'capital': 'Brasília',
           'code': 'BR',
           'continent': 'South America',
           'country_name': 'Brazil',
           'name': 'Brazil, Sao_Paulo',
           'value': 'America/Sao_Paulo'},
          {'capital': 'Brasília',
           'code': 'BR',
           'continent': 'South America',
           'country_name': 'Brazil',
           'name': 'Brazil, Campo_Grande',
           'value': 'America/Campo_Grande'},
          {'capital': 'Brasília',
           'code': 'BR',
           'continent': 'South America',
           'country_name': 'Brazil',
           'name': 'Brazil, Cuiaba',
           'value': 'America/Cuiaba'},
          {'capital': 'Brasília',
           'code': 'BR',
           'continent': 'South America',
           'country_name': 'Brazil',
           'name': 'Brazil, Porto_Velho',
           'value': 'America/Porto_Velho'},
          {'capital': 'Brasília',
           'code': 'BR',
           'continent': 'South America',
           'country_name': 'Brazil',
           'name': 'Brazil, Boa_Vista',
           'value': 'America/Boa_Vista'},
          {'capital': 'Brasília',
           'code': 'BR',
           'continent': 'South America',
           'country_name': 'Brazil',
           'name': 'Brazil, Manaus',
           'value': 'America/Manaus'},
          {'capital': 'Brasília',
           'code': 'BR',
           'continent': 'South America',
           'country_name': 'Brazil',
           'name': 'Brazil, Eirunepe',
           'value': 'America/Eirunepe'},
          {'capital': 'Brasília',
           'code': 'BR',
           'continent': 'South America',
           'country_name': 'Brazil',
           'name': 'Brazil, Rio_Branco',
           'value': 'America/Rio_Branco'},
          {'capital': 'Nassau',
           'code': 'BS',
           'continent': 'North America',
           'country_name': 'Bahamas',
           'name': 'Bahamas, Nassau',
           'value': 'America/Nassau'},
          {'capital': 'Thimphu',
           'code': 'BT',
           'continent': 'Asia',
           'country_name': 'Bhutan',
           'name': 'Bhutan, Thimphu',
           'value': 'Asia/Thimphu'},
          {'capital': 'Gaborone',
           'code': 'BW',
           'continent': 'Africa',
           'country_name': 'Botswana',
           'name': 'Botswana, Gaborone',
           'value': 'Africa/Gaborone'},
          {'capital': 'Minsk',
           'code': 'BY',
           'continent': 'Europe',
           'country_name': 'Belarus',
           'name': 'Belarus, Minsk',
           'value': 'Europe/Minsk'},
          {'capital': 'Belmopan',
           'code': 'BZ',
           'continent': 'North America',
           'country_name': 'Belize',
           'name': 'Belize, Belmopan',
           'value': 'America/Belize'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, St_Johns',
           'value': 'America/St_Johns'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Halifax',
           'value': 'America/Halifax'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Glace_Bay',
           'value': 'America/Glace_Bay'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Moncton',
           'value': 'America/Moncton'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Goose_Bay',
           'value': 'America/Goose_Bay'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Blanc-Sablon',
           'value': 'America/Blanc-Sablon'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Montreal',
           'value': 'America/Montreal'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Toronto',
           'value': 'America/Toronto'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Nipigon',
           'value': 'America/Nipigon'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Thunder_Bay',
           'value': 'America/Thunder_Bay'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Pangnirtung',
           'value': 'America/Pangnirtung'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Iqaluit',
           'value': 'America/Iqaluit'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Atikokan',
           'value': 'America/Atikokan'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Rankin_Inlet',
           'value': 'America/Rankin_Inlet'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Winnipeg',
           'value': 'America/Winnipeg'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Rainy_River',
           'value': 'America/Rainy_River'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Cambridge_Bay',
           'value': 'America/Cambridge_Bay'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Regina',
           'value': 'America/Regina'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Swift_Current',
           'value': 'America/Swift_Current'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Edmonton',
           'value': 'America/Edmonton'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Yellowknife',
           'value': 'America/Yellowknife'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Inuvik',
           'value': 'America/Inuvik'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Dawson_Creek',
           'value': 'America/Dawson_Creek'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Vancouver',
           'value': 'America/Vancouver'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Whitehorse',
           'value': 'America/Whitehorse'},
          {'capital': 'Ottawa',
           'code': 'CA',
           'continent': 'North America',
           'country_name': 'Canada',
           'name': 'Canada, Dawson',
           'value': 'America/Dawson'},
          {'capital': 'Kinshasa',
           'code': 'CD',
           'continent': 'Africa',
           'country_name': 'Democratic Republic of the Congo',
           'name': 'Democratic Republic of the Congo, Kinshasa',
           'value': 'Africa/Kinshasa'},
          {'capital': 'Kinshasa',
           'code': 'CD',
           'continent': 'Africa',
           'country_name': 'Democratic Republic of the Congo',
           'name': 'Democratic Republic of the Congo, Lubumbashi',
           'value': 'Africa/Lubumbashi'},
          {'capital': 'Brazzaville',
           'code': 'CG',
           'continent': 'Africa',
           'country_name': 'Republic of the Congo',
           'name': 'Republic of the Congo, Brazzaville',
           'value': 'Africa/Brazzaville'},
          {'capital': 'Yamoussoukro',
           'code': 'CI',
           'continent': 'Africa',
           'country_name': "Ivory Coast",
           'name': "Ivory Coast, Abidjan",
           'value': 'Africa/Abidjan'},
          {'capital': 'Santiago',
           'code': 'CL',
           'continent': 'South America',
           'country_name': 'Chile',
           'name': 'Chile, Santiago',
           'value': 'America/Santiago'},
          {'capital': 'Santiago',
           'code': 'CL',
           'continent': 'South America',
           'country_name': 'Chile',
           'name': 'Chile, Easter',
           'value': 'Pacific/Easter'},
          {'capital': 'Yaoundé',
           'code': 'CM',
           'continent': 'Africa',
           'country_name': 'Cameroon',
           'name': 'Cameroon, Douala',
           'value': 'Africa/Douala'},
          {'capital': 'Beijing',
           'code': 'CN',
           'continent': 'Asia',
           'country_name': "People's Republic of China",
           'name': "People's Republic of China, Shanghai",
           'value': 'Asia/Shanghai'},
          {'capital': 'Beijing',
           'code': 'CN',
           'continent': 'Asia',
           'country_name': "People's Republic of China",
           'name': "People's Republic of China, Harbin",
           'value': 'Asia/Harbin'},
          {'capital': 'Beijing',
           'code': 'CN',
           'continent': 'Asia',
           'country_name': "People's Republic of China",
           'name': "People's Republic of China, Chongqing",
           'value': 'Asia/Chongqing'},
          {'capital': 'Beijing',
           'code': 'CN',
           'continent': 'Asia',
           'country_name': "People's Republic of China",
           'name': "People's Republic of China, Urumqi",
           'value': 'Asia/Urumqi'},
          {'capital': 'Beijing',
           'code': 'CN',
           'continent': 'Asia',
           'country_name': "People's Republic of China",
           'name': "People's Republic of China, Kashgar",
           'value': 'Asia/Kashgar'},
          {'capital': 'BogotÃ¡',
           'code': 'CO',
           'continent': 'South America',
           'country_name': 'Colombia',
           'name': 'Colombia, Bogota',
           'value': 'America/Bogota'},
          {'capital': 'San José',
           'code': 'CR',
           'continent': 'North America',
           'country_name': 'Costa Rica',
           'name': 'Costa Rica, Costa_Rica',
           'value': 'America/Costa_Rica'},
          {'capital': 'Havana',
           'code': 'CU',
           'continent': 'North America',
           'country_name': 'Cuba',
           'name': 'Cuba, Havana',
           'value': 'America/Havana'},
          {'capital': 'Praia',
           'code': 'CV',
           'continent': 'Africa',
           'country_name': 'Cape Verde',
           'name': 'Cape Verde, Cape_Verde',
           'value': 'Atlantic/Cape_Verde'},
          {'capital': 'Nicosia',
           'code': 'CY',
           'continent': 'Asia',
           'country_name': 'Cyprus',
           'name': 'Cyprus, Nicosia',
           'value': 'Asia/Nicosia'},
          {'capital': 'Prague',
           'code': 'CZ',
           'continent': 'Europe',
           'country_name': 'Czech Republic',
           'name': 'Czech Republic, Prague',
           'value': 'Europe/Prague'},
          {'capital': 'Berlin',
           'code': 'DE',
           'continent': 'Europe',
           'country_name': 'Germany',
           'name': 'Germany, Berlin',
           'value': 'Europe/Berlin'},
          {'capital': 'Djibouti City',
           'code': 'DJ',
           'continent': 'Africa',
           'country_name': 'Djibouti',
           'name': 'Djibouti, Djibouti City',
           'value': 'Africa/Djibouti'},
          {'capital': 'Copenhagen',
           'code': 'DK',
           'continent': 'Europe',
           'country_name': 'Denmark',
           'name': 'Denmark, Copenhagen',
           'value': 'Europe/Copenhagen'},
          {'capital': 'Roseau',
           'code': 'DM',
           'continent': 'North America',
           'country_name': 'Dominica',
           'name': 'Dominica, Roseau',
           'value': 'America/Dominica'},
          {'capital': 'Santo Domingo',
           'code': 'DO',
           'continent': 'North America',
           'country_name': 'Dominican Republic',
           'name': 'Dominican Republic, Santo_Domingo',
           'value': 'America/Santo_Domingo'},
          {'capital': 'Quito',
           'code': 'EC',
           'continent': 'South America',
           'country_name': 'Ecuador',
           'name': 'Ecuador, Guayaquil',
           'value': 'America/Guayaquil'},
          {'capital': 'Quito',
           'code': 'EC',
           'continent': 'South America',
           'country_name': 'Ecuador',
           'name': 'Ecuador, Galapagos',
           'value': 'Pacific/Galapagos'},
          {'capital': 'Tallinn',
           'code': 'EE',
           'continent': 'Europe',
           'country_name': 'Estonia',
           'name': 'Estonia, Tallinn',
           'value': 'Europe/Tallinn'},
          {'capital': 'Cairo',
           'code': 'EG',
           'continent': 'Africa',
           'country_name': 'Egypt',
           'name': 'Egypt, Cairo',
           'value': 'Africa/Cairo'},
          {'capital': 'Asmara',
           'code': 'ER',
           'continent': 'Africa',
           'country_name': 'Eritrea',
           'name': 'Eritrea, Asmera',
           'value': 'Africa/Asmera'},
          {'capital': 'Addis Ababa',
           'code': 'ET',
           'continent': 'Africa',
           'country_name': 'Ethiopia',
           'name': 'Ethiopia, Addis_Ababa',
           'value': 'Africa/Addis_Ababa'},
          {'capital': 'Helsinki',
           'code': 'FI',
           'continent': 'Europe',
           'country_name': 'Finland',
           'name': 'Finland, Helsinki',
           'value': 'Europe/Helsinki'},
          {'capital': 'Suva',
           'code': 'FJ',
           'continent': 'Oceania',
           'country_name': 'Fiji',
           'name': 'Fiji, Suva',
           'value': 'Pacific/Fiji'},
          {'capital': 'Paris',
           'code': 'FR',
           'continent': 'Europe',
           'country_name': 'France',
           'name': 'France, Paris',
           'value': 'Europe/Paris'},
          {'capital': 'Libreville',
           'code': 'GA',
           'continent': 'Africa',
           'country_name': 'Gabon',
           'name': 'Gabon, Libreville',
           'value': 'Africa/Libreville'},
          {'capital': 'Tbilisi',
           'code': 'GE',
           'continent': 'Asia',
           'country_name': 'Georgia',
           'name': 'Georgia, Tbilisi',
           'value': 'Asia/Tbilisi'},
          {'capital': 'Accra',
           'code': 'GH',
           'continent': 'Africa',
           'country_name': 'Ghana',
           'name': 'Ghana, Accra',
           'value': 'Africa/Accra'},
          {'capital': 'Banjul',
           'code': 'GM',
           'continent': 'Africa',
           'country_name': 'The Gambia',
           'name': 'The Gambia, Banjul',
           'value': 'Africa/Banjul'},
          {'capital': 'Conakry',
           'code': 'GN',
           'continent': 'Africa',
           'country_name': 'Guinea',
           'name': 'Guinea, Conakry',
           'value': 'Africa/Conakry'},
          {'capital': 'Athens',
           'code': 'GR',
           'continent': 'Europe',
           'country_name': 'Greece',
           'name': 'Greece, Athens',
           'value': 'Europe/Athens'},
          {'capital': 'Guatemala City',
           'code': 'GT',
           'continent': 'North America',
           'country_name': 'Guatemala',
           'name': 'Guatemala, Guatemala City',
           'value': 'America/Guatemala'},
          {'capital': 'Port-au-Prince',
           'code': 'hT',
           'continent': 'North America',
           'country_name': 'Haiti',
           'name': 'Haiti, Guatemala',
           'value': 'America/Guatemala'},
          {'capital': 'Bissau',
           'code': 'GW',
           'continent': 'Africa',
           'country_name': 'Guinea-Bissau',
           'name': 'Guinea-Bissau, Bissau',
           'value': 'Africa/Bissau'},
          {'capital': 'Georgetown',
           'code': 'GY',
           'continent': 'South America',
           'country_name': 'Guyana',
           'name': 'Guyana, Georgetown',
           'value': 'America/Guyana'},
          {'capital': 'Tegucigalpa',
           'code': 'HN',
           'continent': 'North America',
           'country_name': 'Honduras',
           'name': 'Honduras, Tegucigalpa',
           'value': 'America/Tegucigalpa'},
          {'capital': 'Budapest',
           'code': 'HU',
           'continent': 'Europe',
           'country_name': 'Hungary',
           'name': 'Hungary, Budapest',
           'value': 'Europe/Budapest'},
          {'capital': 'Jakarta',
           'code': 'ID',
           'continent': 'Asia',
           'country_name': 'Indonesia',
           'name': 'Indonesia, Jakarta',
           'value': 'Asia/Jakarta'},
          {'capital': 'Jakarta',
           'code': 'ID',
           'continent': 'Asia',
           'country_name': 'Indonesia',
           'name': 'Indonesia, Pontianak',
           'value': 'Asia/Pontianak'},
          {'capital': 'Jakarta',
           'code': 'ID',
           'continent': 'Asia',
           'country_name': 'Indonesia',
           'name': 'Indonesia, Makassar',
           'value': 'Asia/Makassar'},
          {'capital': 'Jakarta',
           'code': 'ID',
           'continent': 'Asia',
           'country_name': 'Indonesia',
           'name': 'Indonesia, Jayapura',
           'value': 'Asia/Jayapura'},
          {'capital': 'Dublin',
           'code': 'IE',
           'continent': 'Europe',
           'country_name': 'Republic of Ireland',
           'name': 'Republic of Ireland, Dublin',
           'value': 'Europe/Dublin'},
          {'capital': 'Jerusalem',
           'code': 'IL',
           'continent': 'Asia',
           'country_name': 'Israel',
           'name': 'Israel, Jerusalem',
           'value': 'Asia/Jerusalem'},
          {'capital': 'New Delhi',
           'code': 'IN',
           'continent': 'Asia',
           'country_name': 'India',
           'name': 'India, Calcutta',
           'value': 'Asia/Calcutta'},
          {'capital': 'Baghdad',
           'code': 'IQ',
           'continent': 'Asia',
           'country_name': 'Iraq',
           'name': 'Iraq, Baghdad',
           'value': 'Asia/Baghdad'},
          {'capital': 'Tehran',
           'code': 'IR',
           'continent': 'Asia',
           'country_name': 'Iran',
           'name': 'Iran, Tehran',
           'value': 'Asia/Tehran'},
          {'capital': 'Reykjavík',
           'code': 'IS',
           'continent': 'Europe',
           'country_name': 'Iceland',
           'name': 'Iceland, Reykjavik',
           'value': 'Atlantic/Reykjavik'},
          {'capital': 'Rome',
           'code': 'IT',
           'continent': 'Europe',
           'country_name': 'Italy',
           'name': 'Italy, Rome',
           'value': 'Europe/Rome'},
          {'capital': 'Kingston',
           'code': 'JM',
           'continent': 'North America',
           'country_name': 'Jamaica',
           'name': 'Jamaica, Kingston',
           'value': 'America/Jamaica'},
          {'capital': 'Amman',
           'code': 'JO',
           'continent': 'Asia',
           'country_name': 'Jordan',
           'name': 'Jordan, Amman',
           'value': 'Asia/Amman'},
          {'capital': 'Tokyo',
           'code': 'JP',
           'continent': 'Asia',
           'country_name': 'Japan',
           'name': 'Japan, Tokyo',
           'value': 'Asia/Tokyo'},
          {'capital': 'Nairobi',
           'code': 'KE',
           'continent': 'Africa',
           'country_name': 'Kenya',
           'name': 'Kenya, Nairobi',
           'value': 'Africa/Nairobi'},
          {'capital': 'Bishkek',
           'code': 'KG',
           'continent': 'Asia',
           'country_name': 'Kyrgyzstan',
           'name': 'Kyrgyzstan, Bishkek',
           'value': 'Asia/Bishkek'},
          {'capital': 'Tarawa',
           'code': 'KI',
           'continent': 'Oceania',
           'country_name': 'Kiribati',
           'name': 'Kiribati, Tarawa',
           'value': 'Pacific/Tarawa'},
          {'capital': 'Tarawa',
           'code': 'KI',
           'continent': 'Oceania',
           'country_name': 'Kiribati',
           'name': 'Kiribati, Enderbury',
           'value': 'Pacific/Enderbury'},
          {'capital': 'Tarawa',
           'code': 'KI',
           'continent': 'Oceania',
           'country_name': 'Kiribati',
           'name': 'Kiribati, Kiritimati',
           'value': 'Pacific/Kiritimati'},
          {'capital': 'Pyongyang',
           'code': 'KP',
           'continent': 'Asia',
           'country_name': 'North Korea',
           'name': 'North Korea, Pyongyang',
           'value': 'Asia/Pyongyang'},
          {'capital': 'Seoul',
           'code': 'KR',
           'continent': 'Asia',
           'country_name': 'South Korea',
           'name': 'South Korea, Seoul',
           'value': 'Asia/Seoul'},
          {'capital': 'Kuwait City',
           'code': 'KW',
           'continent': 'Asia',
           'country_name': 'Kuwait',
           'name': 'Kuwait, Kuwait City',
           'value': 'Asia/Kuwait'},
          {'capital': 'Beirut',
           'code': 'LB',
           'continent': 'Asia',
           'country_name': 'Lebanon',
           'name': 'Lebanon, Beirut',
           'value': 'Asia/Beirut'},
          {'capital': 'Vaduz',
           'code': 'LI',
           'continent': 'Europe',
           'country_name': 'Liechtenstein',
           'name': 'Liechtenstein, Vaduz',
           'value': 'Europe/Vaduz'},
          {'capital': 'Monrovia',
           'code': 'LR',
           'continent': 'Africa',
           'country_name': 'Liberia',
           'name': 'Liberia, Monrovia',
           'value': 'Africa/Monrovia'},
          {'capital': 'Maseru',
           'code': 'LS',
           'continent': 'Africa',
           'country_name': 'Lesotho',
           'name': 'Lesotho, Maseru',
           'value': 'Africa/Maseru'},
          {'capital': 'Vilnius',
           'code': 'LT',
           'continent': 'Europe',
           'country_name': 'Lithuania',
           'name': 'Lithuania, Vilnius',
           'value': 'Europe/Vilnius'},
          {'capital': 'Luxembourg City',
           'code': 'LU',
           'continent': 'Europe',
           'country_name': 'Luxembourg',
           'name': 'Luxembourg, Luxembourg City',
           'value': 'Europe/Luxembourg'},
          {'capital': 'Riga',
           'code': 'LV',
           'continent': 'Europe',
           'country_name': 'Latvia',
           'name': 'Latvia, Riga',
           'value': 'Europe/Riga'},
          {'capital': 'Tripoli',
           'code': 'LY',
           'continent': 'Africa',
           'country_name': 'Libya',
           'name': 'Libya, Tripoli',
           'value': 'Africa/Tripoli'},
          {'capital': 'Antananarivo',
           'code': 'MG',
           'continent': 'Africa',
           'country_name': 'Madagascar',
           'name': 'Madagascar, Antananarivo',
           'value': 'Indian/Antananarivo'},
          {'capital': 'Majuro',
           'code': 'MH',
           'continent': 'Oceania',
           'country_name': 'Marshall Islands',
           'name': 'Marshall Islands, Majuro',
           'value': 'Pacific/Majuro'},
          {'capital': 'Majuro',
           'code': 'MH',
           'continent': 'Oceania',
           'country_name': 'Marshall Islands',
           'name': 'Marshall Islands, Kwajalein',
           'value': 'Pacific/Kwajalein'},
          {'capital': 'Skopje',
           'code': 'MK',
           'continent': 'Europe',
           'country_name': 'Macedonia',
           'name': 'Macedonia, Skopje',
           'value': 'Europe/Skopje'},
          {'capital': 'Bamako',
           'code': 'ML',
           'continent': 'Africa',
           'country_name': 'Mali',
           'name': 'Mali, Bamako',
           'value': 'Africa/Bamako'},
          {'capital': 'Naypyidaw',
           'code': 'MM',
           'continent': 'Asia',
           'country_name': 'Myanmar',
           'name': 'Myanmar, Rangoon',
           'value': 'Asia/Rangoon'},
          {'capital': 'Ulaanbaatar',
           'code': 'MN',
           'continent': 'Asia',
           'country_name': 'Mongolia',
           'name': 'Mongolia, Ulaanbaatar',
           'value': 'Asia/Ulaanbaatar'},
          {'capital': 'Ulaanbaatar',
           'code': 'MN',
           'continent': 'Asia',
           'country_name': 'Mongolia',
           'name': 'Mongolia, Hovd',
           'value': 'Asia/Hovd'},
          {'capital': 'Ulaanbaatar',
           'code': 'MN',
           'continent': 'Asia',
           'country_name': 'Mongolia',
           'name': 'Mongolia, Choibalsan',
           'value': 'Asia/Choibalsan'},
          {'capital': 'Nouakchott',
           'code': 'MR',
           'continent': 'Africa',
           'country_name': 'Mauritania',
           'name': 'Mauritania, Nouakchott',
           'value': 'Africa/Nouakchott'},
          {'capital': 'Valletta',
           'code': 'MT',
           'continent': 'Europe',
           'country_name': 'Malta',
           'name': 'Malta, Valletta',
           'value': 'Europe/Malta'},
          {'capital': 'Port Louis',
           'code': 'MU',
           'continent': 'Africa',
           'country_name': 'Mauritius',
           'name': 'Mauritius, Port Louis',
           'value': 'Indian/Mauritius'},
          {'capital': 'Malé',
           'code': 'MV',
           'continent': 'Asia',
           'country_name': 'Maldives',
           'name': 'Maldives, Malé',
           'value': 'Indian/Maldives'},
          {'capital': 'Lilongwe',
           'code': 'MW',
           'continent': 'Africa',
           'country_name': 'Malawi',
           'name': 'Malawi, Blantyre',
           'value': 'Africa/Blantyre'},
          {'capital': 'Mexico City',
           'code': 'MX',
           'continent': 'North America',
           'country_name': 'Mexico',
           'name': 'Mexico, Mexico_City',
           'value': 'America/Mexico_City'},
          {'capital': 'Mexico City',
           'code': 'MX',
           'continent': 'North America',
           'country_name': 'Mexico',
           'name': 'Mexico, Cancun',
           'value': 'America/Cancun'},
          {'capital': 'Mexico City',
           'code': 'MX',
           'continent': 'North America',
           'country_name': 'Mexico',
           'name': 'Mexico, Merida',
           'value': 'America/Merida'},
          {'capital': 'Mexico City',
           'code': 'MX',
           'continent': 'North America',
           'country_name': 'Mexico',
           'name': 'Mexico, Monterrey',
           'value': 'America/Monterrey'},
          {'capital': 'Mexico City',
           'code': 'MX',
           'continent': 'North America',
           'country_name': 'Mexico',
           'name': 'Mexico, Mazatlan',
           'value': 'America/Mazatlan'},
          {'capital': 'Mexico City',
           'code': 'MX',
           'continent': 'North America',
           'country_name': 'Mexico',
           'name': 'Mexico, Chihuahua',
           'value': 'America/Chihuahua'},
          {'capital': 'Mexico City',
           'code': 'MX',
           'continent': 'North America',
           'country_name': 'Mexico',
           'name': 'Mexico, Hermosillo',
           'value': 'America/Hermosillo'},
          {'capital': 'Mexico City',
           'code': 'MX',
           'continent': 'North America',
           'country_name': 'Mexico',
           'name': 'Mexico, Tijuana',
           'value': 'America/Tijuana'},
          {'capital': 'Kuala Lumpur',
           'code': 'MY',
           'continent': 'Asia',
           'country_name': 'Malaysia',
           'name': 'Malaysia, Kuala_Lumpur',
           'value': 'Asia/Kuala_Lumpur'},
          {'capital': 'Kuala Lumpur',
           'code': 'MY',
           'continent': 'Asia',
           'country_name': 'Malaysia',
           'name': 'Malaysia, Kuching',
           'value': 'Asia/Kuching'},
          {'capital': 'Maputo',
           'code': 'MZ',
           'continent': 'Africa',
           'country_name': 'Mozambique',
           'name': 'Mozambique, Maputo',
           'value': 'Africa/Maputo'},
          {'capital': 'Windhoek',
           'code': 'NA',
           'continent': 'Africa',
           'country_name': 'Namibia',
           'name': 'Namibia, Windhoek',
           'value': 'Africa/Windhoek'},
          {'capital': 'Niamey',
           'code': 'NE',
           'continent': 'Africa',
           'country_name': 'Niger',
           'name': 'Niger, Niamey',
           'value': 'Africa/Niamey'},
          {'capital': 'Abuja',
           'code': 'NG',
           'continent': 'Africa',
           'country_name': 'Nigeria',
           'name': 'Nigeria, Lagos',
           'value': 'Africa/Lagos'},
          {'capital': 'Managua',
           'code': 'NI',
           'continent': 'North America',
           'country_name': 'Nicaragua',
           'name': 'Nicaragua, Managua',
           'value': 'America/Managua'},
          {'capital': 'Amsterdam',
           'code': 'NL',
           'continent': 'Europe',
           'country_name': 'Kingdom of the Netherlands',
           'name': 'Kingdom of the Netherlands, Amsterdam',
           'value': 'Europe/Amsterdam'},
          {'capital': 'Oslo',
           'code': 'NO',
           'continent': 'Europe',
           'country_name': 'Norway',
           'name': 'Norway, Oslo',
           'value': 'Europe/Oslo'},
          {'capital': 'Kathmandu',
           'code': 'NP',
           'continent': 'Asia',
           'country_name': 'Nepal',
           'name': 'Nepal, Katmandu',
           'value': 'Asia/Katmandu'},
          {'capital': 'Yaren',
           'code': 'NR',
           'continent': 'Oceania',
           'country_name': 'Nauru',
           'name': 'Nauru, Yaren',
           'value': 'Pacific/Nauru'},
          {'capital': 'Wellington',
           'code': 'NZ',
           'continent': 'Oceania',
           'country_name': 'New Zealand',
           'name': 'New Zealand, Auckland',
           'value': 'Pacific/Auckland'},
          {'capital': 'Wellington',
           'code': 'NZ',
           'continent': 'Oceania',
           'country_name': 'New Zealand',
           'name': 'New Zealand, Chatham',
           'value': 'Pacific/Chatham'},
          {'capital': 'Muscat',
           'code': 'OM',
           'continent': 'Asia',
           'country_name': 'Oman',
           'name': 'Oman, Muscat',
           'value': 'Asia/Muscat'},
          {'capital': 'Panama City',
           'code': 'PA',
           'continent': 'North America',
           'country_name': 'Panama',
           'name': 'Panama, Panama City',
           'value': 'America/Panama'},
          {'capital': 'Lima',
           'code': 'PE',
           'continent': 'South America',
           'country_name': 'Peru',
           'name': 'Peru, Lima',
           'value': 'America/Lima'},
          {'capital': 'Port Moresby',
           'code': 'PG',
           'continent': 'Oceania',
           'country_name': 'Papua New Guinea',
           'name': 'Papua New Guinea, Port_Moresby',
           'value': 'Pacific/Port_Moresby'},
          {'capital': 'Manila',
           'code': 'PH',
           'continent': 'Asia',
           'country_name': 'Philippines',
           'name': 'Philippines, Manila',
           'value': 'Asia/Manila'},
          {'capital': 'Islamabad',
           'code': 'PK',
           'continent': 'Asia',
           'country_name': 'Pakistan',
           'name': 'Pakistan, Karachi',
           'value': 'Asia/Karachi'},
          {'capital': 'Warsaw',
           'code': 'PL',
           'continent': 'Europe',
           'country_name': 'Poland',
           'name': 'Poland, Warsaw',
           'value': 'Europe/Warsaw'},
          {'capital': 'Lisbon',
           'code': 'PT',
           'continent': 'Europe',
           'country_name': 'Portugal',
           'name': 'Portugal, Lisbon',
           'value': 'Europe/Lisbon'},
          {'capital': 'Lisbon',
           'code': 'PT',
           'continent': 'Europe',
           'country_name': 'Portugal',
           'name': 'Portugal, Madeira',
           'value': 'Atlantic/Madeira'},
          {'capital': 'Lisbon',
           'code': 'PT',
           'continent': 'Europe',
           'country_name': 'Portugal',
           'name': 'Portugal, Azores',
           'value': 'Atlantic/Azores'},
          {'capital': 'Ngerulmud',
           'code': 'PW',
           'continent': 'Oceania',
           'country_name': 'Palau',
           'name': 'Palau, Ngerulmud',
           'value': 'Pacific/Palau'},
          {'capital': 'Asunción',
           'code': 'PY',
           'continent': 'South America',
           'country_name': 'Paraguay',
           'name': 'Paraguay, Asunción',
           'value': 'America/Asuncion'},
          {'capital': 'Doha',
           'code': 'QA',
           'continent': 'Asia',
           'country_name': 'Qatar',
           'name': 'Qatar, Doha',
           'value': 'Asia/Qatar'},
          {'capital': 'Bucharest',
           'code': 'RO',
           'continent': 'Europe',
           'country_name': 'Romania',
           'name': 'Romania, Bucharest',
           'value': 'Europe/Bucharest'},
          {'capital': 'Moscow',
           'code': 'RU',
           'continent': 'Europe',
           'country_name': 'Russia',
           'name': 'Russia, Kaliningrad',
           'value': 'Europe/Kaliningrad'},
          {'capital': 'Moscow',
           'code': 'RU',
           'continent': 'Europe',
           'country_name': 'Russia',
           'name': 'Russia, Moscow',
           'value': 'Europe/Moscow'},
          {'capital': 'Moscow',
           'code': 'RU',
           'continent': 'Europe',
           'country_name': 'Russia',
           'name': 'Russia, Volgograd',
           'value': 'Europe/Volgograd'},
          {'capital': 'Moscow',
           'code': 'RU',
           'continent': 'Europe',
           'country_name': 'Russia',
           'name': 'Russia, Samara',
           'value': 'Europe/Samara'},
          {'capital': 'Moscow',
           'code': 'RU',
           'continent': 'Europe',
           'country_name': 'Russia',
           'name': 'Russia, Yekaterinburg',
           'value': 'Asia/Yekaterinburg'},
          {'capital': 'Moscow',
           'code': 'RU',
           'continent': 'Europe',
           'country_name': 'Russia',
           'name': 'Russia, Omsk',
           'value': 'Asia/Omsk'},
          {'capital': 'Moscow',
           'code': 'RU',
           'continent': 'Europe',
           'country_name': 'Russia',
           'name': 'Russia, Novosibirsk',
           'value': 'Asia/Novosibirsk'},
          {'capital': 'Moscow',
           'code': 'RU',
           'continent': 'Europe',
           'country_name': 'Russia',
           'name': 'Russia, Krasnoyarsk',
           'value': 'Asia/Krasnoyarsk'},
          {'capital': 'Moscow',
           'code': 'RU',
           'continent': 'Europe',
           'country_name': 'Russia',
           'name': 'Russia, Irkutsk',
           'value': 'Asia/Irkutsk'},
          {'capital': 'Moscow',
           'code': 'RU',
           'continent': 'Europe',
           'country_name': 'Russia',
           'name': 'Russia, Yakutsk',
           'value': 'Asia/Yakutsk'},
          {'capital': 'Moscow',
           'code': 'RU',
           'continent': 'Europe',
           'country_name': 'Russia',
           'name': 'Russia, Vladivostok',
           'value': 'Asia/Vladivostok'},
          {'capital': 'Moscow',
           'code': 'RU',
           'continent': 'Europe',
           'country_name': 'Russia',
           'name': 'Russia, Sakhalin',
           'value': 'Asia/Sakhalin'},
          {'capital': 'Moscow',
           'code': 'RU',
           'continent': 'Europe',
           'country_name': 'Russia',
           'name': 'Russia, Magadan',
           'value': 'Asia/Magadan'},
          {'capital': 'Moscow',
           'code': 'RU',
           'continent': 'Europe',
           'country_name': 'Russia',
           'name': 'Russia, Kamchatka',
           'value': 'Asia/Kamchatka'},
          {'capital': 'Moscow',
           'code': 'RU',
           'continent': 'Europe',
           'country_name': 'Russia',
           'name': 'Russia, Anadyr',
           'value': 'Asia/Anadyr'},
          {'capital': 'Kigali',
           'code': 'RW',
           'continent': 'Africa',
           'country_name': 'Rwanda',
           'name': 'Rwanda, Kigali',
           'value': 'Africa/Kigali'},
          {'capital': 'Riyadh',
           'code': 'SA',
           'continent': 'Asia',
           'country_name': 'Saudi Arabia',
           'name': 'Saudi Arabia, Riyadh',
           'value': 'Asia/Riyadh'},
          {'capital': 'Honiara',
           'code': 'SB',
           'continent': 'Oceania',
           'country_name': 'Solomon Islands',
           'name': 'Solomon Islands, Guadalcanal',
           'value': 'Pacific/Guadalcanal'},
          {'capital': 'Victoria',
           'code': 'SC',
           'continent': 'Africa',
           'country_name': 'Seychelles',
           'name': 'Seychelles, Mahe',
           'value': 'Indian/Mahe'},
          {'capital': 'Khartoum',
           'code': 'SD',
           'continent': 'Africa',
           'country_name': 'Sudan',
           'name': 'Sudan, Khartoum',
           'value': 'Africa/Khartoum'},
          {'capital': 'Stockholm',
           'code': 'SE',
           'continent': 'Europe',
           'country_name': 'Sweden',
           'name': 'Sweden, Stockholm',
           'value': 'Europe/Stockholm'},
          {'capital': 'Singapore',
           'code': 'SG',
           'continent': 'Asia',
           'country_name': 'Singapore',
           'name': 'Singapore, Singapore',
           'value': 'Asia/Singapore'},
          {'capital': 'Ljubljana',
           'code': 'SI',
           'continent': 'Europe',
           'country_name': 'Slovenia',
           'name': 'Slovenia, Ljubljana',
           'value': 'Europe/Ljubljana'},
          {'capital': 'Bratislava',
           'code': 'SK',
           'continent': 'Europe',
           'country_name': 'Slovakia',
           'name': 'Slovakia, Bratislava',
           'value': 'Europe/Bratislava'},
          {'capital': 'Freetown',
           'code': 'SL',
           'continent': 'Africa',
           'country_name': 'Sierra Leone',
           'name': 'Sierra Leone, Freetown',
           'value': 'Africa/Freetown'},
          {'capital': 'San Marino',
           'code': 'SM',
           'continent': 'Europe',
           'country_name': 'San Marino',
           'name': 'San Marino, San_Marino',
           'value': 'Europe/San_Marino'},
          {'capital': 'Dakar',
           'code': 'SN',
           'continent': 'Africa',
           'country_name': 'Senegal',
           'name': 'Senegal, Dakar',
           'value': 'Africa/Dakar'},
          {'capital': 'Mogadishu',
           'code': 'SO',
           'continent': 'Africa',
           'country_name': 'Somalia',
           'name': 'Somalia, Mogadishu',
           'value': 'Africa/Mogadishu'},
          {'capital': 'Paramaribo',
           'code': 'SR',
           'continent': 'South America',
           'country_name': 'Suriname',
           'name': 'Suriname, Paramaribo',
           'value': 'America/Paramaribo'},
          {'capital': 'Damascus',
           'code': 'SY',
           'continent': 'Asia',
           'country_name': 'Syria',
           'name': 'Syria, Damascus',
           'value': 'Asia/Damascus'},
          {'capital': 'Lomé',
           'code': 'TG',
           'continent': 'Africa',
           'country_name': 'Togo',
           'name': 'Togo, Lomé',
           'value': 'Africa/Lome'},
          {'capital': 'Bangkok',
           'code': 'TH',
           'continent': 'Asia',
           'country_name': 'Thailand',
           'name': 'Thailand, Bangkok',
           'value': 'Asia/Bangkok'},
          {'capital': 'Dushanbe',
           'code': 'TJ',
           'continent': 'Asia',
           'country_name': 'Tajikistan',
           'name': 'Tajikistan, Dushanbe',
           'value': 'Asia/Dushanbe'},
          {'capital': 'Ashgabat',
           'code': 'TM',
           'continent': 'Asia',
           'country_name': 'Turkmenistan',
           'name': 'Turkmenistan, Ashgabat',
           'value': 'Asia/Ashgabat'},
          {'capital': 'Tunis',
           'code': 'TN',
           'continent': 'Africa',
           'country_name': 'Tunisia',
           'name': 'Tunisia, Tunis',
           'value': 'Africa/Tunis'},
          {'capital': 'Nukuʻalofa',
           'code': 'TO',
           'continent': 'Oceania',
           'country_name': 'Tonga',
           'name': 'Tonga, Nukuʻalofa',
           'value': 'Pacific/Tongatapu'},
          {'capital': 'Ankara',
           'code': 'TR',
           'continent': 'Asia',
           'country_name': 'Turkey',
           'name': 'Turkey, Istanbul',
           'value': 'Europe/Istanbul'},
          {'capital': 'Port of Spain',
           'code': 'TT',
           'continent': 'North America',
           'country_name': 'Trinidad and Tobago',
           'name': 'Trinidad and Tobago, Port_of_Spain',
           'value': 'America/Port_of_Spain'},
          {'capital': 'Funafuti',
           'code': 'TV',
           'continent': 'Oceania',
           'country_name': 'Tuvalu',
           'name': 'Tuvalu, Funafuti',
           'value': 'Pacific/Funafuti'},
          {'capital': 'Dodoma',
           'code': 'TZ',
           'continent': 'Africa',
           'country_name': 'Tanzania',
           'name': 'Tanzania, Dar_es_Salaam',
           'value': 'Africa/Dar_es_Salaam'},
          {'capital': 'Kiev',
           'code': 'UA',
           'continent': 'Europe',
           'country_name': 'Ukraine',
           'name': 'Ukraine, Kiev',
           'value': 'Europe/Kiev'},
          {'capital': 'Kiev',
           'code': 'UA',
           'continent': 'Europe',
           'country_name': 'Ukraine',
           'name': 'Ukraine, Uzhgorod',
           'value': 'Europe/Uzhgorod'},
          {'capital': 'Kiev',
           'code': 'UA',
           'continent': 'Europe',
           'country_name': 'Ukraine',
           'name': 'Ukraine, Zaporozhye',
           'value': 'Europe/Zaporozhye'},
          {'capital': 'Kiev',
           'code': 'UA',
           'continent': 'Europe',
           'country_name': 'Ukraine',
           'name': 'Ukraine, Simferopol',
           'value': 'Europe/Simferopol'},
          {'capital': 'Kampala',
           'code': 'UG',
           'continent': 'Africa',
           'country_name': 'Uganda',
           'name': 'Uganda, Kampala',
           'value': 'Africa/Kampala'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, New_York',
           'value': 'America/New_York'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Detroit',
           'value': 'America/Detroit'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Louisville',
           'value': 'America/Kentucky/Louisville'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Monticello',
           'value': 'America/Kentucky/Monticello'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Indianapolis',
           'value': 'America/Indiana/Indianapolis'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Marengo',
           'value': 'America/Indiana/Marengo'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Knox',
           'value': 'America/Indiana/Knox'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Vevay',
           'value': 'America/Indiana/Vevay'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Chicago',
           'value': 'America/Chicago'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Vincennes',
           'value': 'America/Indiana/Vincennes'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Petersburg',
           'value': 'America/Indiana/Petersburg'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Menominee',
           'value': 'America/Menominee'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Center',
           'value': 'America/North_Dakota/Center'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, New_Salem',
           'value': 'America/North_Dakota/New_Salem'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Denver',
           'value': 'America/Denver'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Boise',
           'value': 'America/Boise'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Shiprock',
           'value': 'America/Shiprock'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Phoenix',
           'value': 'America/Phoenix'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Los Angeles',
           'value': 'America/Los_Angeles'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Anchorage',
           'value': 'America/Anchorage'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Juneau',
           'value': 'America/Juneau'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Yakutat',
           'value': 'America/Yakutat'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Nome',
           'value': 'America/Nome'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Adak',
           'value': 'America/Adak'},
          {'capital': 'Washington, D.C.',
           'code': 'US',
           'continent': 'North America',
           'country_name': 'United States',
           'name': 'United States, Honolulu',
           'value': 'Pacific/Honolulu'},
          {'capital': 'Montevideo',
           'code': 'UY',
           'continent': 'South America',
           'country_name': 'Uruguay',
           'name': 'Uruguay, Montevideo',
           'value': 'America/Montevideo'},
          {'capital': 'Tashkent',
           'code': 'UZ',
           'continent': 'Asia',
           'country_name': 'Uzbekistan',
           'name': 'Uzbekistan, Samarkand',
           'value': 'Asia/Samarkand'},
          {'capital': 'Tashkent',
           'code': 'UZ',
           'continent': 'Asia',
           'country_name': 'Uzbekistan',
           'name': 'Uzbekistan, Tashkent',
           'value': 'Asia/Tashkent'},
          {'capital': 'Vatican City',
           'code': 'VA',
           'continent': 'Europe',
           'country_name': 'Vatican City',
           'name': 'Vatican City, Vatican',
           'value': 'Europe/Vatican'},
          {'capital': 'Caracas',
           'code': 'VE',
           'continent': 'South America',
           'country_name': 'Venezuela',
           'name': 'Venezuela, Caracas',
           'value': 'America/Caracas'},
          {'capital': 'Hanoi',
           'code': 'VN',
           'continent': 'Asia',
           'country_name': 'Vietnam',
           'name': 'Vietnam, Saigon',
           'value': 'Asia/Saigon'},
          {'capital': 'Port Vila',
           'code': 'VU',
           'continent': 'Oceania',
           'country_name': 'Vanuatu',
           'name': 'Vanuatu, Efate',
           'value': 'Pacific/Efate'},
          {'capital': "Sana'a",
           'code': 'YE',
           'continent': 'Asia',
           'country_name': 'Yemen',
           'name': 'Yemen, Aden',
           'value': 'Asia/Aden'},
          {'capital': 'Lusaka',
           'code': 'ZM',
           'continent': 'Africa',
           'country_name': 'Zambia',
           'name': 'Zambia, Lusaka',
           'value': 'Africa/Lusaka'},
          {'capital': 'Harare',
           'code': 'ZW',
           'continent': 'Africa',
           'country_name': 'Zimbabwe',
           'name': 'Zimbabwe, Harare',
           'value': 'Africa/Harare'},
          {'capital': 'Algiers',
           'code': 'DZ',
           'continent': 'Africa',
           'country_name': 'Algeria',
           'name': 'Algeria, Algiers',
           'value': 'Africa/Algiers'},
          {'capital': 'Sarajevo',
           'code': 'BA',
           'continent': 'Europe',
           'country_name': 'Bosnia and Herzegovina',
           'name': 'Bosnia and Herzegovina, Sarajevo',
           'value': 'Europe/Sarajevo'},
          {'capital': 'Phnom Penh',
           'code': 'KH',
           'continent': 'Asia',
           'country_name': 'Cambodia',
           'name': 'Cambodia, Phnom_Penh',
           'value': 'Asia/Phnom_Penh'},
          {'capital': 'Bangui',
           'code': 'CF',
           'continent': 'Africa',
           'country_name': 'Central African Republic',
           'name': 'Central African Republic, Bangui',
           'value': 'Africa/Bangui'},
          {'capital': "N'Djamena",
           'code': 'TD',
           'continent': 'Africa',
           'country_name': 'Chad',
           'name': 'Chad, Ndjamena',
           'value': 'Africa/Ndjamena'},
          {'capital': 'Moroni',
           'code': 'KM',
           'continent': 'Africa',
           'country_name': 'Comoros',
           'name': 'Comoros, Comoro',
           'value': 'Indian/Comoro'},
          {'capital': 'Zagreb',
           'code': 'HR',
           'continent': 'Europe',
           'country_name': 'Croatia',
           'name': 'Croatia, Zagreb',
           'value': 'Europe/Zagreb'},
          {'capital': 'Dili',
           'code': 'TL',
           'continent': 'Asia',
           'country_name': 'East Timor',
           'name': 'East Timor, Dili',
           'value': 'Asia/Dili'},
          {'capital': 'San Salvador',
           'code': 'SV',
           'continent': 'North America',
           'country_name': 'El Salvador',
           'name': 'El Salvador, El_Salvador',
           'value': 'America/El_Salvador'},
          {'capital': 'Malabo',
           'code': 'GQ',
           'continent': 'Africa',
           'country_name': 'Equatorial Guinea',
           'name': 'Equatorial Guinea, Malabo',
           'value': 'Africa/Malabo'},
          {'capital': "St. George's",
           'code': 'GD',
           'continent': 'North America',
           'country_name': 'Grenada',
           'name': "Grenada, St. George's",
           'value': 'America/Grenada'},
          {'capital': 'Astana',
           'code': 'KZ',
           'continent': 'Asia',
           'country_name': 'Kazakhstan',
           'name': 'Kazakhstan, Almaty',
           'value': 'Asia/Almaty'},
          {'capital': 'Astana',
           'code': 'KZ',
           'continent': 'Asia',
           'country_name': 'Kazakhstan',
           'name': 'Kazakhstan, Qyzylorda',
           'value': 'Asia/Qyzylorda'},
          {'capital': 'Astana',
           'code': 'KZ',
           'continent': 'Asia',
           'country_name': 'Kazakhstan',
           'name': 'Kazakhstan, Aqtobe',
           'value': 'Asia/Aqtobe'},
          {'capital': 'Astana',
           'code': 'KZ',
           'continent': 'Asia',
           'country_name': 'Kazakhstan',
           'name': 'Kazakhstan, Aqtau',
           'value': 'Asia/Aqtau'},
          {'capital': 'Astana',
           'code': 'KZ',
           'continent': 'Asia',
           'country_name': 'Kazakhstan',
           'name': 'Kazakhstan, Oral',
           'value': 'Asia/Oral'},
          {'capital': 'Vientiane',
           'code': 'LA',
           'continent': 'Asia',
           'country_name': 'Laos',
           'name': 'Laos, Vientiane',
           'value': 'Asia/Vientiane'},
          {'capital': 'Palikir',
           'code': 'FM',
           'continent': 'Oceania',
           'country_name': 'Federated States of Micronesia',
           'name': 'Federated States of Micronesia, Truk',
           'value': 'Pacific/Truk'},
          {'capital': 'Palikir',
           'code': 'FM',
           'continent': 'Oceania',
           'country_name': 'Federated States of Micronesia',
           'name': 'Federated States of Micronesia, Ponape',
           'value': 'Pacific/Ponape'},
          {'capital': 'Palikir',
           'code': 'FM',
           'continent': 'Oceania',
           'country_name': 'Federated States of Micronesia',
           'name': 'Federated States of Micronesia, Kosrae',
           'value': 'Pacific/Kosrae'},
          {'capital': 'Chisinau',
           'code': 'MD',
           'continent': 'Europe',
           'country_name': 'Moldova',
           'name': 'Moldova, Chisinau',
           'value': 'Europe/Chisinau'},
          {'capital': 'Monaco',
           'code': 'MC',
           'continent': 'Europe',
           'country_name': 'Monaco',
           'name': 'Monaco, Monaco',
           'value': 'Europe/Monaco'},
          {'capital': 'Podgorica',
           'code': 'ME',
           'continent': 'Europe',
           'country_name': 'Montenegro',
           'name': 'Montenegro, Podgorica',
           'value': 'Europe/Podgorica'},
          {'capital': 'Rabat',
           'code': 'MA',
           'continent': 'Africa',
           'country_name': 'Morocco',
           'name': 'Morocco, Casablanca',
           'value': 'Africa/Casablanca'},
          {'capital': 'Basseterre',
           'code': 'KN',
           'continent': 'North America',
           'country_name': 'Saint Kitts and Nevis',
           'name': 'Saint Kitts and Nevis, St_Kitts',
           'value': 'America/St_Kitts'},
          {'capital': 'Castries',
           'code': 'LC',
           'continent': 'North America',
           'country_name': 'Saint Lucia',
           'name': 'Saint Lucia, St_Lucia',
           'value': 'America/St_Lucia'},
          {'capital': 'Kingstown',
           'code': 'VC',
           'continent': 'North America',
           'country_name': 'Saint Vincent and the Grenadines',
           'name': 'Saint Vincent and the Grenadines, St_Vincent',
           'value': 'America/St_Vincent'},
          {'capital': 'Apia',
           'code': 'WS',
           'continent': 'Oceania',
           'country_name': 'Samoa',
           'name': 'Samoa, Apia',
           'value': 'Pacific/Apia'},
          {'capital': 'Belgrade',
           'code': 'RS',
           'continent': 'Europe',
           'country_name': 'Serbia',
           'name': 'Serbia, Belgrade',
           'value': 'Europe/Belgrade'},
          {'capital': 'Pretoria',
           'code': 'ZA',
           'continent': 'Africa',
           'country_name': 'South Africa',
           'name': 'South Africa, Johannesburg',
           'value': 'Africa/Johannesburg'},
          {'capital': 'Madrid',
           'code': 'ES',
           'continent': 'Europe',
           'country_name': 'Spain',
           'name': 'Spain, Madrid',
           'value': 'Europe/Madrid'},
          {'capital': 'Madrid',
           'code': 'ES',
           'continent': 'Europe',
           'country_name': 'Spain',
           'name': 'Spain, Ceuta',
           'value': 'Africa/Ceuta'},
          {'capital': 'Madrid',
           'code': 'ES',
           'continent': 'Europe',
           'country_name': 'Spain',
           'name': 'Spain, Canary',
           'value': 'Atlantic/Canary'},
          {'capital': 'Sri Jayewardenepura Kotte',
           'code': 'LK',
           'continent': 'Asia',
           'country_name': 'Sri Lanka',
           'name': 'Sri Lanka, Colombo',
           'value': 'Asia/Colombo'},
          {'capital': 'Mbabane',
           'code': 'SZ',
           'continent': 'Africa',
           'country_name': 'Swaziland',
           'name': 'Swaziland, Mbabane',
           'value': 'Africa/Mbabane'},
          {'capital': 'Bern',
           'code': 'CH',
           'continent': 'Europe',
           'country_name': 'Switzerland',
           'name': 'Switzerland, Zurich',
           'value': 'Europe/Zurich'},
          {'capital': 'Abu Dhabi',
           'code': 'AE',
           'continent': 'Asia',
           'country_name': 'United Arab Emirates',
           'name': 'United Arab Emirates, Dubai',
           'value': 'Asia/Dubai'},
          {'capital': 'London',
           'code': 'GB',
           'continent': 'Europe',
           'country_name': 'United Kingdom',
           'name': 'United Kingdom, London',
           'value': 'Europe/London'}]

# remove underscores from names
for tz in tzlist_useful:
    tz['name'] = tz['name'].replace('_', ' ')

def common_timezones_useful(country=None, keep=None):
    """Get a list of common timezones with useful metadata (see tzlist)."""
    tzs = tzlist_useful

    keep_tz = None
    if keep:
        ktzl = [t for t in tzs if t['value'] == keep]
        if ktzl:
            keep_tz = ktzl[0]
        else:
            log.error(f"common_timezones_useful asked to preserve invalid time zone name {keep}")

    # filter by common
    common_set = pytz.common_timezones_set
    tzs = [tz for tz in tzs if tz['value'] in common_set]

    # filter by country if specified
    if country:
        ctzs = pytz.country_timezones(country)
        tzs = [tz for tz in tzs if tz['value'] in ctzs]

    # add `keep` if it isn't in the list
    if keep_tz and keep_tz not in tzs:
        tzs.append(keep_tz)

    return tzs
